⚙️ ci(release.yaml): update CI workflow to improve Node.js and Python setup
- Remove redundant Node.js setup steps and streamline the installation
process.
- Update Python setup to fetch poetry installation and dependencies.
- Enhance logic for handling branch creation and PR title generation.
- Implement caching for Node.js and Python dependencies.
- Add unit test execution step with poetry.

Signed-off-by: David Hooton <david@hooton.org>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -16,10 +16,44 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Fetch the main branch
+        run: |
+          git fetch origin main:main
+
+      - name: Setup Python
+        uses: actions/setup-python@v5.1.0
+        with:
+          python-version: "3.x"
+
+      - name: Load Python cache
+        uses: actions/cache@v4.0.2
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/poetry.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-cache-
+
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python3 -
+          echo "Poetry installed"
+          which poetry
+
+      - name: Install Dependencies
+        run: |
+          make install-dev
+          echo "NODE_MAJOR_VERSION=$(make node-major-version)" >> $GITHUB_ENV
+
+      - name: Run Unit Tests
+        run: |
+          poetry run pytest
+        env:
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: "22.4.1"
+          node-version: ${{ env.NODE_MAJOR_VERSION }}
 
       - name: Load Node.js cache
         uses: actions/cache@v4.0.2
@@ -32,25 +66,6 @@ jobs:
       - name: Install Node.js dependencies
         run: |
           npm install
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.x"
-
-      - name: Load Python cache
-        uses: actions/cache@v4.0.2
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.in') }}
-          restore-keys: |
-                ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.in') }}
-                ${{ runner.os }}-pip-cache-
-
-      - name: Install Python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install setuptools wheel twine packaging build toml
 
       - name: Authenticate GitHub CLI
         run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
@@ -66,75 +81,60 @@ jobs:
           PYPI_USER_AGENT: ${{ secrets.PYPI_USER_AGENT }}
         run: ./.github/workflows/semantic-release.sh
 
-  create-release-pr:
-    runs-on: ubuntu-latest
-    needs: release
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4.1.7
-        with:
-          fetch-depth: 0 # Fetch all branches
-
-      - name: Setup Python
-        uses: actions/setup-python@v5.1.0
-        with:
-          python-version: "3.x"
-
-      - name: Load Python cache
-        uses: actions/cache@v4.0.2
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-cache
-          restore-keys: |
-            ${{ runner.os }}-pip-cache
-
-      - name: Set up environment variables
-        run: |
-          # Setup GITHUB_TOKEN
-          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
-          # Setup GH_TOKEN
-          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
-          # Setup OpenAI API Key
-          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
-          # Get Current PR Title
-          PR_TITLE=$(gh pr list --json title --jq '.[0].title' || echo "")
-          # Sanitize PR_TITLE to remove problematic characters
-          SANITIZED_PR_TITLE=$(echo "$PR_TITLE" | tr -d '\n' | tr -d '\r' | tr -d '"')
-          echo "PR_TITLE=$SANITIZED_PR_TITLE" >> $GITHUB_ENV
-          echo "PR TITLE: $PR_TITLE"
-        env:
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-
-      - name: Configure Git & Login to GitHub CLI
-        run: |
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-
-      - name: Compile Python requirements
-        run: make install
-
-      - name: Run Unit Tests
-        run: make test
-
-      # Check if PR exists, if it doesn't create one with a generated title using
-      # pr-title-generate
       - name: Create or Update PR
         id: pr
         run: |
           SOURCE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-          PR_URL=$(gh pr list --head $SOURCE_BRANCH --json url --jq '.[0].url' || echo "")
-          PR_TITLE=$(pr-title-generate)
-          echo "PR_TITLE: $PR_TITLE"
-          BASE_BRANCH="main"
-          if [ -z "$PR_URL" ]; then
-            PR_URL=$(gh pr create --title "Release $SOURCE_BRANCH" --body "This PR was automatically generated by a GitHub Action" --base $BASE_BRANCH --head $SOURCE_BRANCH)
-            echo "PR_URL: $PR_URL"
+
+          # Determine BASE_BRANCH based on SOURCE_BRANCH
+          if [ "$SOURCE_BRANCH" = "release" ]; then
+              BASE_BRANCH="main"
+          elif [[ "$SOURCE_BRANCH" == pre-release-* ]]; then
+              BASE_BRANCH="release"
+          elif [[ "$SOURCE_BRANCH" == dev-* ]]; then
+              BASE_BRANCH="pre-release"
+          else
+              BASE_BRANCH="release"
           fi
-          PR_BODY=$(python3 .github/workflows/pr_body_gen.py $SOURCE_BRANCH $BASE_BRANCH)
+
+          # Check if BASE_BRANCH exists, if not, create it based on 'release' or 'main'
+          if ! git rev-parse --verify origin/$BASE_BRANCH >/dev/null 2>&1; then
+              echo "Base branch '$BASE_BRANCH' does not exist. Creating it."
+              if [ "$BASE_BRANCH" = "pre-release" ]; then
+                  git checkout -b $BASE_BRANCH origin/release || git checkout -b $BASE_BRANCH origin/main
+                  git push origin $BASE_BRANCH
+              else
+                  echo "Error: Cannot determine the branch to base '$BASE_BRANCH' from."
+                  exit 1
+              fi
+          fi
+
+          # Debugging output
+          echo "SOURCE_BRANCH: $SOURCE_BRANCH"
+          echo "BASE_BRANCH: $BASE_BRANCH"
+
+          # Check for commits between branches
+          COMMITS=$(git log $BASE_BRANCH..$SOURCE_BRANCH)
+          if [ -z "$COMMITS" ]; then
+              echo "Error: No commits between $SOURCE_BRANCH and $BASE_BRANCH."
+              exit 1
+          fi
+
+          # Create or update PR
+          PR_URL=$(gh pr list --head $SOURCE_BRANCH --json url --jq '.[0].url' || echo "")
+          PR_TITLE=$(poetry run pr-title-generate)
+          echo "PR_TITLE: $PR_TITLE"
+
+          if [ -z "$PR_URL" ]; then
+              PR_URL=$(gh pr create --title "$PR_TITLE" --body "This PR was automatically generated by a GitHub Action" --base $BASE_BRANCH)
+              echo "PR_URL: $PR_URL"
+          fi
+
+          PR_BODY=$(poetry run python3 .github/workflows/pr_body_gen.py $SOURCE_BRANCH $BASE_BRANCH)
           gh pr edit $PR_URL --title "$PR_TITLE" --body "$PR_BODY"
-        shell: /usr/bin/bash -e {0}
         env:
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_TITLE: ${{ env.PR_TITLE }}
+        shell: /usr/bin/bash -e {0}
